---
title: "COVID-19 Analysis"
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    navbar:
      - {title: "LinkedIn", icon: "fa-linkedin", align: right, href: "https://www.linkedin.com/in/tylorbunting/"}
      - {title: "Source Code", icon: "fa-github", align: right, href: "https://github.com/tylorbunting/COVID19_Analysis"}
      - {title: "Data Source", icon: "fa-database", align: right, href: "https://github.com/CSSEGISandData/COVID-19"}
---

```{r setup, include=FALSE}
library("flexdashboard")
library("plotly")
library("readr")
library("httr")
library("tidyr")
library("dplyr")
library("lubridate")
library("ggplot2")
library("purrr")
library("RColorBrewer")
source("Extract_Data.R")

No_of_Countrys <- 6


```


Australian Overview
===================================== 

Row {data-height=150}
-----------------------------------------------------------------------

### Confirmed

```{r}
valueBox(sum(Data_Australia_Max_Locations_Co$Count), 
         icon = "fa-frown-o",
         color = "primary")

```

### Recovered

```{r}
valueBox(sum(Data_Australia_Max_Locations_Re$Count), 
         icon = "fa-medkit",
         color = "success")

```

### Deaths

```{r}
valueBox(sum(Data_Australia_Max_Locations_De$Count), 
         icon = "fa-times-circle",
         color = "danger")
```

### Last Updated

```{r}
valueBox(format(max(Data_Australia$Dates), "%Y/%m/%d"), 
         icon = "fa-clock",
         color = "primary")
```


Row {data-height=350 .tabset .tabset-fade}
-----------------------------------------------------------------------

### Total Number of Confirmed Cases 

```{r}

Data_Australia_Max_Locations_Co <- Data_Australia_Max_Locations_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

Data_Australia_Max_Locations_Co <- Data_Australia_Max_Locations_Co %>%
      filter(Location %in% unique(Data_Australia_Max_Locations_Co$Location))

ggplotly(Data_Australia_Max_Locations_Co %>%
    ggplot(aes(x = Location, y = Count, fill = Location)) +
    geom_bar(stat = "identity") +
    scale_fill_hue() +
    theme_minimal() +
    labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Locations in Australia"), y = "") +
    theme(legend.position = "none") +
    geom_text(label = Data_Australia_Max_Locations_Co$Count, nudge_y = 50) +
    scale_y_continuous(limits = c(0, max(Data_Australia_Co$Count) + (0.10 * max(Data_Australia_Co$Count)))) +
    scale_fill_manual(values = brewer.pal(9, "Blues")[3:9]))
  

```


### Total Number of Recoverd Cases 

```{r}

Data_Australia_Max_Locations_Co <- Data_Australia_Max_Locations_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

Data_Australia_Max_Locations_Re <- Data_Australia_Max_Locations_Re %>%
      filter(Location %in% unique(Data_Australia_Max_Locations_Co$Location))

ggplotly(Data_Australia_Max_Locations_Re %>%
    ggplot(aes(x = Location, y = Count, fill = Location)) +
    geom_bar(stat = "identity") +
    scale_fill_hue() +
    theme_minimal() +
    labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Locations in Australia"), y = "") +
    theme(legend.position = "none") +
    geom_text(label = Data_Australia_Max_Locations_Re$Count, nudge_y = 50) +
    scale_y_continuous(limits = c(0, max(Data_Australia_Co$Count) + (0.10 * max(Data_Australia_Co$Count)))) +
    scale_fill_manual(values = brewer.pal(9, "Greens")[3:9]))
  

```


### Total Number of Cases Resulted in Death 

```{r}

Data_Australia_Max_Locations_Co <- Data_Australia_Max_Locations_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

Data_Australia_Max_Locations_De <- Data_Australia_Max_Locations_De %>%
      filter(Location %in% unique(Data_Australia_Max_Locations_Co$Location))

ggplotly(Data_Australia_Max_Locations_De %>%
    ggplot(aes(x = Location, y = Count, fill = Location)) +
    geom_bar(stat = "identity") +
    scale_fill_hue() +
    theme_minimal() +
    labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Locations in Australia"), y = "") +
    theme(legend.position = "none") +
    geom_text(label = Data_Australia_Max_Locations_De$Count, nudge_y = 50) +
    scale_y_continuous(limits = c(0, max(Data_Australia_Co$Count) + (0.10 * max(Data_Australia_Co$Count)))) +
    scale_fill_brewer(palette="Reds"))
  

```

Row {data-height=550 .tabset .tabset-fade}
-----------------------------------------------------------------------

### Confirmed Cases Overtime

```{r}

Data_Australia_Max_Locations_Co <- Data_Australia_Max_Locations_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

Data_Australia_Co <- Data_Australia_Co %>%
      filter(Location %in% unique(Data_Australia_Max_Locations_Co$Location))

ggplotly(Data_Australia_Co %>%
          ggplot(aes(x = Dates, y = Count, fill = Location)) +
          geom_area(size = 1L) +
          scale_fill_hue() +
          theme_minimal() +
          labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Locations in Australia"), y = "") +
          theme(legend.position = "none") +
          facet_wrap(vars(Location)) +
          scale_x_date(date_breaks = "1 months", date_labels = "%b") +
          scale_fill_manual(values = brewer.pal(9, "Blues")[3:9]))


```


### Recovered Cases Overtime

```{r}

Data_Australia_Max_Locations_Co <- Data_Australia_Max_Locations_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

Data_Australia_Re <- Data_Australia_Re %>%
      filter(Location %in% unique(Data_Australia_Max_Locations_Co$Location))

ggplotly(Data_Australia_Re %>%
            group_by(Location, Dates) %>%
            summarise(Count = sum(Count)) %>%            
            ggplot(aes(x = Dates, y = Count, fill = Location)) +
            geom_area(size = 1L) +
            scale_fill_hue() +
            theme_minimal() +
            labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Countries Globally"), y = "") +
            theme(legend.position = "none") +
            facet_wrap(vars(Location)) +
            scale_x_date(date_breaks = "1 months", date_labels = "%b") +
            scale_fill_manual(values = brewer.pal(9, "Greens")[3:9]))


```


### Death Cases Overtime

```{r}

Data_Australia_Max_Locations_Co <- Data_Australia_Max_Locations_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

Data_Australia_De <- Data_Australia_De %>%
      filter(Location %in% unique(Data_Australia_Max_Locations_Co$Location))

ggplotly(Data_Australia_De %>%
            group_by(Location, Dates) %>%
            summarise(Count = sum(Count)) %>%            
            ggplot(aes(x = Dates, y = Count, fill = Location)) +
            geom_area(size = 1L) +
            scale_fill_hue() +
            theme_minimal() +
            labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Countries Globally"), y = "") +
            theme(legend.position = "none") +
            facet_wrap(vars(Location)) +
            scale_x_date(date_breaks = "1 months", date_labels = "%b") +
            scale_fill_brewer(palette="Reds"))

```


Global Overview
===================================== 


Row {data-height=150}
-----------------------------------------------------------------------

### Confirmed

```{r}

valueBox(sum(Data_Global_Max_Country_Co$Count, na.rm = TRUE), 
         icon = "fa-frown-o",
         color = "primary")

```


### Recovered

```{r}


valueBox(sum(Data_Global_Max_Country_Re$Count, na.rm = TRUE), 
         icon = "fa-medkit",
         color = "success")

```

### Deaths

```{r}
valueBox(sum(Data_Global_Max_Country_De$Count, na.rm = TRUE), 
         icon = "fa-times-circle",
         color = "danger")
```

### Last Updated

```{r}
valueBox(format(max(Data_Global$Dates), "%Y/%m/%d"), 
         icon = "fa-clock",
         color = "primary")
```

Row {data-height=350 .tabset .tabset-fade}
-----------------------------------------------------------------------

### Total Number of Confirmed Cases 

```{r}

Data_Global_Max_Country_Co <- Data_Global_Max_Country_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

ggplotly(Data_Global_Max_Country_Co %>%
    ggplot(aes(x = Country, y = Count, fill = Country)) +
    geom_bar(stat = "identity") +
    scale_fill_hue() +
    theme_minimal() +
    labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Countries Globally"), y = "") +
    theme(legend.position = "none") +
    geom_text(label = Data_Global_Max_Country_Co$Count, nudge_y = 5000) +
    scale_y_continuous(limits = c(0, max(Data_Global_Max_Country_Co$Count) + (0.10 * max(Data_Global_Max_Country_Co$Count)))) +
    scale_fill_manual(values = brewer.pal(9, "Blues")[3:9]))

```


### Total Number of Recoverd Cases 

```{r}

Data_Global_Max_Country_Co <- Data_Global_Max_Country_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

Data_Global_Max_Country_Re <- Data_Global_Max_Country_Re %>%
      filter(Country %in% unique(Data_Global_Max_Country_Co$Country))

ggplotly(Data_Global_Max_Country_Re %>%
    ggplot(aes(x = Country, y = Count, fill = Country)) +
    geom_bar(stat = "identity") +
    scale_fill_hue() +
    theme_minimal() +
    labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Countries Globally"), y = "") +
    theme(legend.position = "none") +
    geom_text(label = Data_Global_Max_Country_Re$Count, nudge_y = 5000) +
    scale_y_continuous(limits = c(0, max(Data_Global_Max_Country_Co$Count) + (0.10 * max(Data_Global_Max_Country_Co$Count)))) +
    scale_fill_manual(values = brewer.pal(9, "Greens")[3:9]))
  

```


### Total Number of Cases Resulted in Death 

```{r}


Data_Global_Max_Country_Co <- Data_Global_Max_Country_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

Data_Global_Max_Country_De <- Data_Global_Max_Country_De %>%
      filter(Country %in% unique(Data_Global_Max_Country_Co$Country))

ggplotly(Data_Global_Max_Country_De %>%
    ggplot(aes(x = Country, y = Count, fill = Country)) +
    geom_bar(stat = "identity") +
    scale_fill_hue() +
    theme_minimal() +
    labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Countries Globally"), y = "") +
    theme(legend.position = "none") +
    geom_text(label = Data_Global_Max_Country_De$Count, nudge_y = 5000) +
    scale_y_continuous(limits = c(0, max(Data_Global_Max_Country_Co$Count) + (0.10 * max(Data_Global_Max_Country_Co$Count)))) +
    scale_fill_brewer(palette="Reds"))
  

```

Row {data-height=550 .tabset .tabset-fade}
-----------------------------------------------------------------------

### Confirmed Cases Overtime

```{r}

Data_Global_Max_Country_Co <- Data_Global_Max_Country_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

Data_Global_Co <- Data_Global_Co %>%
      filter(Country %in% unique(Data_Global_Max_Country_Co$Country))

ggplotly(Data_Global_Co %>%
           group_by(Country, Dates) %>%
           summarise(Count = sum(Count)) %>%
            ggplot(aes(x = Dates, y = Count, fill = Country)) +
            geom_area(size = 1L) +
            scale_fill_hue() +
            theme_minimal() +
            labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Countries Globally"), y = "") +
            theme(legend.position = "none") +
            facet_wrap(vars(Country)) +
            scale_x_date(date_breaks = "1 months", date_labels = "%b") +
            scale_fill_manual(values = brewer.pal(9, "Blues")[3:9]))


```


### Recovered Cases Overtime

```{r}

Data_Global_Max_Country_Co <- Data_Global_Max_Country_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

Data_Global_Re <- Data_Global_Re %>%
      filter(Country %in% unique(Data_Global_Max_Country_Co$Country))

ggplotly(Data_Global_Re %>%
            group_by(Country, Dates) %>%
            summarise(Count = sum(Count)) %>%
            ggplot(aes(x = Dates, y = Count, fill = Country)) +
            geom_area(size = 1L) +
            scale_fill_hue() +
            theme_minimal() +
            labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Countries Globally"), y = "") +
            theme(legend.position = "none") +
            facet_wrap(vars(Country)) +
            scale_x_date(date_breaks = "1 months", date_labels = "%b") +
            scale_fill_manual(values = brewer.pal(9, "Greens")[3:9]))


```


### Death Cases Overtime

```{r}

Data_Global_Max_Country_Co <- Data_Global_Max_Country_Co %>%
      arrange(desc(Count)) %>%
      head(No_of_Countrys)

Data_Global_De <- Data_Global_De %>%
      filter(Country %in% unique(Data_Global_Max_Country_Co$Country))

ggplotly(Data_Global_De %>%
            group_by(Country, Dates) %>%
            summarise(Count = sum(Count)) %>%            
            ggplot(aes(x = Dates, y = Count, fill = Country)) +
            geom_area(size = 1L) +
            scale_fill_hue() +
            theme_minimal() +
            labs(title = "", x = paste0("Top ", No_of_Countrys," Highest Countries Globally"), y = "") +
            theme(legend.position = "none") +
            facet_wrap(vars(Country)) +
            scale_x_date(date_breaks = "1 months", date_labels = "%b") +
            scale_fill_brewer(palette="Reds"))




```
